### ISSUE TITLE
Libva-Utils fails to compile with GCC 7.1.1

### ISSUE THREAD

**Issue by stripes416** [01org/libva-utils#52]
```
22:29:22,331 INFO  - test_va_api_init_terminate.cpp: In member function 'void VAAPI::VAAPIInitTerminate::doInitTerminate()':
22:29:22,331 INFO  - test_va_api_init_terminate.cpp:41:8: error: suggest explicit braces to avoid ambiguous 'else' [-Werror=dangling-else]
22:29:22,331 INFO  - if (vaDisplay)
22:29:22,331 INFO  - ^
```

**Comment by uartie** [comment]
This is a side-effect from the GTEST macros not enclosing the entire macro definition inside braces.  We should only have to add braces in our **if** statement to fix this (e.g. **if(...) { ... }**)

**Comment by uartie** [comment]
https://github.com/google/googletest/issues/1119
